name: Windows

on: [push]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        julia-version: ['1.3.0']
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Build Package
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(url=\"https://github.com/shinolab/AUTD3.jl\")); Pkg.build(\"AUTD3\")'
